server:
  port: 2828

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/ 
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot
    username: root
    password: root
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 15
      pool-name: HikariCP
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*" 
        
        
logging:
  level:
    com:
      app: DEBUG
    org:
      springframewor: OFF
      hibernate: OFF
  file: myapp.log
    
            
        
        
        
        
        
        
      